== Using Gradle

=== Invoking Gradle using the wrapper

[source]
----
./gradlew hello
----

Note the implicit invocation from the project root.
With Gradle, no need to navigate inside project directories.
Instead, you can pass a specific task name and path to execute.

=== Invoking tasks

[source]
----
./gradlew [taskName...] [--option-name...]
----

Where `taskName` is one or more tasks names, space separated.

Each task can also reference a specific task in a subproject:

[source]
----
./gradlew :server:test
----

=== Discovering tasks

[source]
----
./gradlew tasks
----

Will list all the tasks defined by the project, with a description

=== Getting help on a task

[source]
----
./gradlew help --task <taskName>
----

Will list all projects having the task and give some usage context.

=== Exclude a task

* `--exclude-task` or `-x`
** To exclude one task from the execution graph
[source]
----
./gradlew build -x test
----

NOTE: This will exclude the specific task _and_ all tasks it depended upon

=== Continue a build

* `--continue`
** To continue with the build even when a task fails
[source]
----
./gradlew test --continue
----

NOTE: The dependents task(s) of the failed one will still not be executed.

=== Continuous build

* `--continuous` or `-t`
** Runs the tasks every time the input changes
[source]
----
./gradlew -t test
----

NOTE: Use `<CTRL>-D` to stop the build

=== Logging

[%step]
* Gradle defines 6 log levels: `error`, `quiet`, `warning`, `lifecycle`, `info`, `debug`
* Default log level (`lifecycle`) is minimalistic

=== Configuring logging

* Command line flags allow to set a different level:
[source]
----
$ gradle hello -i
$ gradle -q hello
----

NOTE: When troubleshooting, `info` is usually enough, `debug` has a _lot_ of output.

=== Convention tasks

Gradle built-in plugins define a set of convention tasks.

These are used as as entry points to request execution of canonical project operations.

=== `assemble` task

This convention task indicates that all output producing tasks have to be executed.

=== `check` task

This convention task indicates that all verification tasks are to be executed.

=== `build` task

This convention task triggers `assemble` and `check`.

=== No task argument?

[source]
----
./gradlew
----

The above will invoke the `help` task by default.

However a project can define a set of default tasks to be run when it is invoked without a task argument.

[source, groovy]
----
include::{buildsdir}/default.gradle[]
----

=== Gradle daemon

By default, Gradle will start a background process to execute your builds.

This allows to have a warmed up JVM running your build instead of having a fresh one each time.

[%step]
* `org.gradle.daemon` can be used to disable the daemon
* `org.gradle.daemon.idletimeout` can be used to tweak the idle time

=== Parallel builds

Gradle can run tasks of decoupled projects in parallel

[%step]
* `org.gradle.parallel` can be used to disable parallel mode
* `org.gradle.workers.max` can be used to limit the number of workers used by parallel builds
** Defaults to number of CPUs

[%notitle]
[state=demo]
=== Demo 2.1

Demo

[NOTE.speaker]
--
Cover:

* Invocation camel case
* One or more tasks
* Think result instead of lifecycle
--