== Using Gradle

=== Invoking Gradle using the wrapper

[source]
----
./gradlew hello
----

Note the implicit invocation from the project root.
With Gradle, no need to navigate inside project directories.
Instead, you can pass a specific task name and path to execute.

=== Invoking tasks

[source]
----
./gradlew [taskName...] [--option-name...]
----

Where `taskName` is one or more tasks names, space separated.

Each task can also reference a specific task in a subproject:

[source]
----
./gradlew :server:test
----

=== Discovering tasks

[source]
----
./gradlew tasks
----

Will list all the tasks defined by the project, with a description

=== Getting help on a task

[source]
----
./gradlew help --task <taskName>
----

Will list all projects having the task and give some usage context.

=== Exclude a task

* `--exclude-task` or `-x`
** To exclude one task from the execution graph
[source]
----
./gradlew build -x test
----

NOTE: This will exclude the specific task _and_ all tasks it depended upon

=== Continue a build

* `--continue`
** To continue with the build even when a task fails
[source]
----
./gradlew test --continue
----

NOTE: The dependents task(s) of the failed one will still not be executed.

=== Continuous build

* `--continuous` or `-t`
** Runs the tasks every time the input changes
[source]
----
./gradlew -t test
----

NOTE: Use `<CTRL>-D` to stop the build

=== Lifecycle

++++
<div style="font-size:medium">
++++

[cols="a,a,3a"]
|===
|Maven |Gradle |Description

|clean
|clean
|Removes the outputs of tasks

|compile
|classes
|Generates the classes from source files

|test
|test
|Executes unit tests

|===

++++
</div>
++++

=== Lifecycle

++++
<div style="font-size:medium">
++++

[cols="a,a,3a"]
|===
|Maven |Gradle |Description

|package
|assemble
|Creates a jar

|verify
|check
|Runs all tests, integration tests, quality checks, ...

|install
|publishToMavenLocal
|Gradle doesn't need a local repository, but should you need Maven interoperability, you can add the `maven-publish` plugin to add this task

|deploy
|publishToMavenRepository
|This tasks is _not_ available by default, as it depends on which type of repository you deploy to. In general you just apply the `maven-publish` plugin to add this task

|===

++++
</div>
++++

=== Gradle daemon

By default, Gradle will start a background process to execute your builds.

This allows to have a warmed up JVM running your build instead of having a fresh one each time.

* `org.gradle.daemon` can be used to disable the daemon
* `org.gradle.daemon.idletimeout` can be used to tweak the idle time

=== Parallel builds

Gradle can run tasks of decoupled projects in parallel

* `org.gradle.parallel` can be used to disable parallel mode
* `org.gradle.workers.max` can be used to limit the number of workers used by parallel builds
** Defaults to number of CPUs
