== Using Gradle

=== Invoking Gradle using the wrapper

[source]
----
./gradlew hello
----

Note the implicit invocation from the project root.
With Gradle, no need to navigate inside project directories.
Instead, you can pass a specific task name and path to execute.

=== Invoking tasks

[source]
----
./gradlew [taskName...] [--option-name...]
----

Where `taskName` is one or more tasks names, space separated.

Each task can also reference a specific task in a subproject:

[source]
----
./gradlew :server:test
----

=== Discovering tasks

[source]
----
./gradlew tasks
----

Will list all the tasks defined by the project, with a description

=== Getting help on a task

[source]
----
./gradlew help --task <taskName>
----

Will list all projects having the task and give some usage context.

=== Exclude a task

* `--exclude-task` or `-x`
** To exclude one task from the execution graph
[source]
----
./gradlew build -x test
----

NOTE: This will exclude the specific task _and_ all tasks it depended upon

=== Continue a build

* `--continue`
** To continue with the build even when a task fails
[source]
----
./gradlew test --continue
----

NOTE: The dependents task(s) of the failed one will still not be executed.

=== Continuous build

* `--continuous` or `-t`
** Runs the tasks every time the input changes
[source]
----
./gradlew -t test
----

NOTE: Use `<CTRL>-D` to stop the build

=== Logging

* Gradle defines 6 log levels: `error`, `quiet`, `warning`, `lifecycle`, `info`, `debug`
* Default log level (`lifecycle`) is minimalistic

=== Configuring logging

* Command line flags allow to set a different level:
[source]
----
> gradle hello -i
> gradle -q hello
----

NOTE: When troubleshooting, `info` is usually enough, `debug` has a _lot_ of output.

[%notitle]
[state=demo]
=== Demo 2.1

Demo

[NOTE.speaker]
--
Cover:

* Invocation camel case
* One or more tasks
* Think result instead of lifecycle
--