== Advanced configuration

=== Declarative vs. Imperative

The ability to have code inside Gradle build scripts is a powerful feature.

While it adds flexibility, abusing the feature leads to builds that are hard to understand.

=== Gradle extensibility

* Define properties
* Add _extensions_ to existing objects

Allows built in domain objects to be extended, including `Project`.

Makes the _build language_ extensible.

=== Gradle properties

[%step]
* Different levels
* Matching different use cases

=== `gradle.properties` and command line

* Define items that have a sensible default

[source, groovy]
----
org.gradle.parallel = true
deployUrl = https://example.com/default
----

Can be overridden on the command line:
[source]
----
./gradlew -Dorg.gradle.parallel=false -PdeployUrl='https://example.com/custom'
----

=== Project properties

* Added to the `ext` container

[source, groovy]
----
include::{buildsdir}/ext.gradle[]
----

=== Extensions

[source, groovy]
----
include::{buildsdir}/extension.gradle[]
----

=== Configuration rules

[source, groovy]
----
include::{buildsdir}/confRules.gradle[]
----

=== Implicit task relationships

Tasks can have implicit dependencies:

* `taskA.inputs = taskB.outputs`
** `jar` task consumes `compileJava` output

This is known by Gradle through task implementations.

The heart of the Gradle execution model.

=== Explicit task relationships

[source, groovy]
----
include::{buildsdir}/depends.gradle[]
----

Aim for having implicit dependencies, based on proper modelling, instead of having to resort to explicit wiring.

[%notitle]
[state=demo]
=== Demo 3.2

Demo

[NOTE.speaker]
--
* Try to replace compile.dependsOn generated with file collection and then fully implicit
--

=== SourceSet output

Source sets have an `output` property. It references:

* Class files
* Processed resources

[source, groovy]
----
task jar {
  from sourceSets.main.output
}
----

=== Script plugins

.plugin.gradle
[source, groovy]
----
include::{buildsdir}/plugin.gradle[]
----

.master.gradle
[source, groovy]
----
include::{buildsdir}/master.gradle[]
----

Note: the script reference can be a URL

=== Binary plugins

* Implementation of the `Plugin` interface
* Can be bundled in `buildSrc`
* Can extend the Gradle model
** New task types, extensions, ...

=== Build code management

* Use script plugins to decompose build scripts
** Enhances comprehension and allows for reuse
** Modularize according to domain (integ tests) or role (user/build admin)
* Encapsulate the imperative into plugins and custom tasks
* Enhance the API of the Gradle domain objects
* Add your own declarative elements